const dataImgDefault = [
  { id: 1, src: "./img/g1.jpg" },
  { id: 2, src: "./img/g2.jpg" },
  { id: 3, src: "./img/g3.jpg" },
  { id: 4, src: "./img/g4.jpg" },
  { id: 5, src: "./img/g5.jpg" },
  { id: 6, src: "./img/g6.jpg" },
  { id: 7, src: "./img/g7.jpg" },
  { id: 8, src: "./img/g8.jpg" },
  { id: 9, src: "./img/g9.jpg" },
  { id: 10, src: "./img/g10.jpg" },
  { id: 11, src: "./img/g11.jpg" },
  { id: 12, src: "./img/g12.jpg" },
  { id: 13, src: "./img/g13.jpg" },
  { id: 14, src: "./img/g14.jpg" },
];
